# Example configuration.yaml entry
mqtt:
  light:
    - name: Wortuhr
      unique_id: "wortuhr"
      schema: template
      effect_list:
        - Wordclock
        - Seconds
        - Digitalclock
        - Scrollingtext
        - Rainbowcycle
        - Rainbow
        - Color
      command_topic: "ESPWordclock"
      # state_topic: "ESPWordclock"
      command_on_template: >
        {"state": "on"
        {%- if red is defined and green is defined and blue is defined -%}
        , "color": [{{ red }}, {{ green }}, {{ blue }}]
        {%- endif -%}
        {%- if effect is defined -%}
        , "effect": "{{ effect }}"
        {%- endif -%}
        }
      command_off_template: '{"state": "off"}'
      state_template: '{{ value_json.state }}'
      red_template: '{{ value_json.color[0] }}'
      green_template: '{{ value_json.color[1] }}'
      blue_template: '{{ value_json.color[2] }}'
      effect_template: '{{ value_json.effect }}'